env:
  name: CartPole-v1
  num_envs: 16
  max_episode_steps: 1000


algo:
  name: sac
  gamma: 0.99
  lr: 3e-4
  batch_size: 256
  seed: 42
  buffer_size: 10000
  warmup_buffer_size: 1000


sampler:
  name: epsilon_greedy
  starting_epsilon: 0.1
  ending_epsilon: 0.01
  warmup_steps: 1000 


networks:
  q_1:
    network_type: mlp
    network_args:
      hidden_dims: [64, 64]
      activations: [relu, relu, relu]
      bias: False

  q_2:
    network_type: mlp
    network_args:
      hidden_dims: [64, 64]
      activations: [relu, relu, relu]
      bias: False

  policy:
    network_type: mlp
    network_args:
      hidden_dims: [64, 64]
      activations: [relu, relu, relu]
      bias: False

  value_network:
    network_type: mlp
    network_args:
      hidden_dims: [64, 64]
      activations: [relu, relu, relu]
      bias: False

  target_value_network:
    network_type: mlp
    network_args:
      hidden_dims: [64, 64]
      activations: [relu, relu, relu]
      bias: False


train:
  total_env_steps: 50000
  eval_interval: 5000
  wandb_project: rl-benchmarking
  wandb_group: cartpole-v1_sac
  wandb_run: cartpole-v1_sac_run1
  save_video_last_eval: True