env:
  name: CartPole-v1
  num_envs: 16
  max_episode_steps: 1000


algo:
  name: ddqn
  gamma: 0.99
  lr: 3e-4
  batch_size: 64
  seed: 42
  buffer_size: 5000
  warmup_buffer_size: 1000
  overwrite_target_net_grad_updates: 100   # In terms of 'number grad updates', not samples seen 


sampler:
  name: epsilon_greedy
  starting_epsilon: 0.1
  ending_epsilon: 0.01
  warmup_steps: 1000 


networks:
  q_1:
    network_type: mlp
    network_args:
      hidden_dims: [64, 64]
      activations: [relu, relu, relu]
      bias: False

  q_2:
    network_type: mlp
    network_args:
      hidden_dims: [64, 64]
      activations: [relu, relu, relu]
      bias: False


train:
  total_env_steps: 50000
  eval_interval: 5000
  eval_envs: 128
  wandb_project: rl-benchmarking
  wandb_group: cartpole-v1_ddqn